# Generated by Django 4.1.6 on 2023-05-02 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Campaign",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("subject", models.CharField(max_length=255)),
                ("preview_text", models.CharField(max_length=255)),
                ("article_url", models.URLField()),
                ("html_content", models.TextField()),
                ("plain_text_content", models.TextField()),
                ("published_date", models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name="Subscriber",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("email_verified", models.BooleanField(default=False)),
                ("first_name", models.CharField(max_length=255)),
                ("active", models.BooleanField(default=True)),
            ],
        ),
    ]
